server: zeroth
also-write-to-file: true

database:
  host: localhost
  port: 3306
  database: barbatos-storybook
  user: root
  password: passwd
  prefix: "storybook_"
  usessl: false
  properties:
    connection-timeout: 60000
    validation-timeout: 3000
    idle-timeout: 60000
    login-timeout: 10
    maxLifeTime: 60000
    maximum-pool-size: 8
    minimum-idle: 2
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useUnicode: true
    characterEncoding: utf8
    allowPublicKeyRetrieval: true

submitted: "&x&a&6&7&1&1&2你将书轻轻放好并合上了盖子，里面的书本渐渐地化为了闪烁着点点光斑，散落开来..."
success-write-into-database: "&x&4&0&9&6&9&7你感受到有一阵轻风吹过，将你心中的话语带向了未知的远方..."
failure: "&c似乎在处理你的留言时出现了一点错误，联系一下服务器管理员吧！"

openbook: |
  &f===================================
    &8作者: &7%s
    &8标题：&7%s
    &8撰写于：&7%s
  &f===================================
  

